#ifndef LOGPLUGIN_GLOBAL_H
#define LOGPLUGIN_GLOBAL_H

#if defined(LOGPLUGIN_LIBRARY)
#  define LOGPLUGIN_EXPORT Q_DECL_EXPORT
#else
#  define LOGPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // LOGPLUGIN_GLOBAL_H
