#ifndef LOGPLUGINS_GLOBAL_H
#define LOGPLUGINS_GLOBAL_H

#if defined(LOGPLUGINS_LIBRARY)
#  define LOGPLUGINS_EXPORT Q_DECL_EXPORT
#else
#  define LOGPLUGINS_EXPORT Q_DECL_IMPORT
#endif

#endif // LOGPLUGINS_GLOBAL_H
